// =============================================================================
// normalization_suggestions.js - generated by betika_mongodb_normalized (2026-10-08T16:59:04Z)
//
// Converts fields with inconsistent scalar BSON types to their dominant type
// (the type observed most often in the sample). Run on the TARGET after the
// data load. DRY-RUN unless BMN_APPLY=1: it only counts affected documents.
//
// Usage:
//   [BMN_APPLY=1] [BMN_DB=<target_db>] mongosh "<target-uri>" --quiet --norc \
//     --file normalization_suggestions.js
//
// Conversions use $convert with onError: <original value>, so documents that
// cannot be converted are left untouched and reported as remaining.
// ALWAYS validate with the application owners before applying.
// =============================================================================

const FIXES = [];

const APPLY = String(process.env.BMN_APPLY || '0') === '1';
const ONLY_DB = String(process.env.BMN_DB || '');
const C = process.env.NO_COLOR
  ? { r: '', g: '', y: '', b: '', c: '', d: '', x: '' }
  : { r: '\x1b[31m', g: '\x1b[32m', y: '\x1b[33m', b: '\x1b[34m', c: '\x1b[36m', d: '\x1b[2m', x: '\x1b[0m' };

let errors = 0;
const out = (color, tag, msg) => print(`${color}[${tag}]${C.x} ${msg}`);

out(C.b, 'INFO', `normalization | mode=${APPLY ? 'APPLY' : 'DRY-RUN'} | fixes=${FIXES.length}`);
for (const f of FIXES) {
  if (ONLY_DB && ONLY_DB !== f.db) continue;
  const ns = `${f.db}.${f.collection}`;
  const coll = db.getSiblingDB(f.db).getCollection(f.collection);
  const others = Object.keys(f.types).filter((t) => t !== f.dominant_type);
  const filter = { [f.path]: { $type: others } };
  const update = [{
    $set: { [f.path]: { $convert: { input: `$${f.path}`, to: f.dominant_type, onError: `$${f.path}`, onNull: null } } },
  }];
  try {
    const n = coll.countDocuments(filter);
    if (!APPLY) {
      out(C.c, 'PLAN', `${ns} ${f.path}: ${n} doc(s) ${others.join('/')} -> ${f.dominant_type} ${C.d}<- ${f.instance}:${f.source_ns}${C.x}`);
      continue;
    }
    const res = coll.updateMany(filter, update);
    const left = coll.countDocuments(filter);
    const tag = left > 0 ? `${C.y}${left} not convertible${C.x}` : 'all converted';
    out(C.g, ' OK ', `${ns} ${f.path}: matched=${res.matchedCount} modified=${res.modifiedCount} (${tag})`);
  } catch (e) {
    errors += 1;
    out(C.r, 'FAIL', `${ns} ${f.path}: ${e.message}`);
  }
}
quit(errors > 0 ? 1 : 0);
