// =============================================================================
// target_bootstrap.js - generated by betika_mongodb_normalized (2026-10-08T16:59:04Z)
//
// Pre-creates the normalized layout on the central (target) instance.
// DRY-RUN unless BMN_APPLY=1. Every phase is idempotent (existing objects are skipped).
//
// Usage:
//   BMN_PHASE=<phase> [BMN_APPLY=1] [BMN_DB=<target_db>] \
//     mongosh "<target-uri>" --quiet --norc --file target_bootstrap.js
//
// Phases, in execution order around the data load:
//   collections  create collections (options, validators, collation) + shard keys
//   (data load)  migration_commands.sh  (--noIndexRestore --bypassDocumentValidation)
//   indexes      create secondary indexes (TTL deletions start at this point)
//   views        create views (after their source collections exist)
//   security     create custom roles and users (prompts for every password)
//   verify       compare target document counts with the source snapshot counts
//
// Environment:
//   BMN_APPLY=1   execute changes (default: dry-run, prints the plan)
//   BMN_DB=name   restrict the phase to a single target database
//   NO_COLOR=1    disable ANSI colors
// =============================================================================

const PLAN = {
  "generated_at": "2026-10-08T16:59:04Z",
  "target": null,
  "target_sharded": false,
  "collections": [
    {
      "db": "cd_betika_cd",
      "name": "recon.config.doc.extension",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 2,
      "source": "cd:betika_cd.recon.config.doc.extension"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.config.doc.type",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 2,
      "source": "cd:betika_cd.recon.config.doc.type"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.config.field",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 5,
      "source": "cd:betika_cd.recon.config.field"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.config.filter",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 18,
      "source": "cd:betika_cd.recon.config.filter"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.config.job",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 22,
      "source": "cd:betika_cd.recon.config.job"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.config.provider",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 17,
      "source": "cd:betika_cd.recon.config.provider"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.config.settlement",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 25,
      "source": "cd:betika_cd.recon.config.settlement"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.config.transaction.type",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 2,
      "source": "cd:betika_cd.recon.config.transaction.type"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.config.transfer.expiry",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 1,
      "source": "cd:betika_cd.recon.config.transfer.expiry"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.history",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 16766,
      "source": "cd:betika_cd.recon.history"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.job",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 39,
      "source": "cd:betika_cd.recon.job"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.job.entries",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 23338,
      "source": "cd:betika_cd.recon.job.entries"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.job.info",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 12192,
      "source": "cd:betika_cd.recon.job.info"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.notification",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 13,
      "source": "cd:betika_cd.recon.notification"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.progress",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 66,
      "source": "cd:betika_cd.recon.progress"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.provider",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 4,
      "source": "cd:betika_cd.recon.provider"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.provider.query",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 8,
      "source": "cd:betika_cd.recon.provider.query"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.stage",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 82,
      "source": "cd:betika_cd.recon.stage"
    },
    {
      "db": "cd_betika_cd",
      "name": "recon.transfer",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 6,
      "source": "cd:betika_cd.recon.transfer"
    },
    {
      "db": "gh_betika_gh",
      "name": "user",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 1,
      "source": "gh:betika_gh.user"
    },
    {
      "db": "ke_betika_favorites",
      "name": "favorites",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 3,
      "source": "ke:betika_favorites.favorites"
    },
    {
      "db": "ke_betika_help_center",
      "name": "kb",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 29,
      "source": "ke:betika_help_center.kb"
    },
    {
      "db": "ke_betika_help_center",
      "name": "users",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 4,
      "source": "ke:betika_help_center.users"
    },
    {
      "db": "ke_betika_help_center",
      "name": "votes",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 124802,
      "source": "ke:betika_help_center.votes"
    },
    {
      "db": "ke_recon-engine",
      "name": "recon.config.doc.extension",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 2,
      "source": "ke:recon-engine.recon.config.doc.extension"
    },
    {
      "db": "ke_recon-engine",
      "name": "recon.config.doc.type",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 2,
      "source": "ke:recon-engine.recon.config.doc.type"
    },
    {
      "db": "ke_recon-engine",
      "name": "recon.config.field",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 5,
      "source": "ke:recon-engine.recon.config.field"
    },
    {
      "db": "ke_recon-engine",
      "name": "recon.config.filter",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 7,
      "source": "ke:recon-engine.recon.config.filter"
    },
    {
      "db": "ke_recon-engine",
      "name": "recon.config.job",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 8,
      "source": "ke:recon-engine.recon.config.job"
    },
    {
      "db": "ke_recon-engine",
      "name": "recon.config.provider",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 7,
      "source": "ke:recon-engine.recon.config.provider"
    },
    {
      "db": "ke_recon-engine",
      "name": "recon.config.settlement",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 7,
      "source": "ke:recon-engine.recon.config.settlement"
    },
    {
      "db": "ke_recon-engine",
      "name": "recon.config.transaction.type",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 2,
      "source": "ke:recon-engine.recon.config.transaction.type"
    },
    {
      "db": "ke_recon-engine",
      "name": "recon.config.transfer.expiry",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 1,
      "source": "ke:recon-engine.recon.config.transfer.expiry"
    },
    {
      "db": "ke_recon-engine",
      "name": "recon.history",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 632,
      "source": "ke:recon-engine.recon.history"
    },
    {
      "db": "ke_recon-engine",
      "name": "recon.job.entries",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 3435,
      "source": "ke:recon-engine.recon.job.entries"
    },
    {
      "db": "ke_recon-engine",
      "name": "recon.job.info",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 1736,
      "source": "ke:recon-engine.recon.job.info"
    },
    {
      "db": "ke_recon-engine",
      "name": "test",
      "type": "collection",
      "options": {},
      "shard_key": null,
      "shard_unique": false,
      "expected_documents": 0,
      "source": "ke:recon-engine.test"
    }
  ],
  "indexes": [],
  "views": [],
  "roles": [
    {
      "role": "bmnSchemaAuditor",
      "db": "admin",
      "privileges": [
        {
          "resource": {
            "cluster": true
          },
          "actions": [
            "getParameter",
            "inprog",
            "listDatabases",
            "serverStatus"
          ]
        },
        {
          "resource": {
            "db": "",
            "collection": ""
          },
          "actions": [
            "collStats",
            "find",
            "listCollections",
            "listIndexes",
            "viewRole",
            "viewUser"
          ]
        },
        {
          "resource": {
            "db": "config",
            "collection": "collections"
          },
          "actions": [
            "find"
          ]
        }
      ],
      "roles": [],
      "sources": [
        "cd",
        "gh",
        "ke",
        "mw",
        "tz",
        "ug"
      ]
    },
    {
      "role": "explainRole",
      "db": "admin",
      "privileges": [
        {
          "resource": {
            "db": "",
            "collection": ""
          },
          "actions": [
            "collStats",
            "dbHash",
            "dbStats",
            "find",
            "listCollections",
            "listIndexes"
          ]
        },
        {
          "resource": {
            "db": "",
            "collection": "system.version"
          },
          "actions": [
            "find"
          ]
        }
      ],
      "roles": [],
      "sources": [
        "cd",
        "gh",
        "ke",
        "mw",
        "tz",
        "ug"
      ]
    },
    {
      "role": "oplogReader",
      "db": "admin",
      "privileges": [
        {
          "resource": {
            "db": "local",
            "collection": "oplog.rs"
          },
          "actions": [
            "find"
          ]
        }
      ],
      "roles": [],
      "sources": [
        "cd",
        "gh",
        "ke",
        "mw",
        "tz",
        "ug"
      ]
    },
    {
      "role": "pbmAnyAction",
      "db": "admin",
      "privileges": [
        {
          "resource": {
            "anyResource": true
          },
          "actions": [
            "anyAction"
          ]
        }
      ],
      "roles": [],
      "sources": [
        "mw"
      ]
    }
  ],
  "users": [
    {
      "user": "admin",
      "db": "admin",
      "roles": [
        {
          "role": "root",
          "db": "admin"
        }
      ],
      "sources": [
        "cd",
        "gh",
        "ke",
        "mw",
        "tz",
        "ug"
      ]
    },
    {
      "user": "betikaknowlegebase_app",
      "db": "admin",
      "roles": [
        {
          "role": "root",
          "db": "admin"
        }
      ],
      "sources": [
        "tz"
      ]
    },
    {
      "user": "mongodb_exporter",
      "db": "admin",
      "roles": [
        {
          "role": "clusterMonitor",
          "db": "admin"
        },
        {
          "role": "read",
          "db": "local"
        }
      ],
      "sources": [
        "cd",
        "gh",
        "ke",
        "mw",
        "tz"
      ]
    },
    {
      "user": "pbmuser",
      "db": "admin",
      "roles": [
        {
          "role": "backup",
          "db": "admin"
        },
        {
          "role": "clusterMonitor",
          "db": "admin"
        },
        {
          "role": "pbmAnyAction",
          "db": "admin"
        },
        {
          "role": "readWrite",
          "db": "admin"
        },
        {
          "role": "restore",
          "db": "admin"
        }
      ],
      "sources": [
        "mw"
      ]
    },
    {
      "user": "pmm_monitor",
      "db": "admin",
      "roles": [
        {
          "role": "clusterMonitor",
          "db": "admin"
        },
        {
          "role": "explainRole",
          "db": "admin"
        },
        {
          "role": "read",
          "db": "local"
        }
      ],
      "sources": [
        "cd",
        "gh",
        "ke",
        "mw",
        "tz",
        "ug"
      ]
    },
    {
      "user": "recon-engine_app",
      "db": "admin",
      "roles": [
        {
          "role": "readWrite",
          "db": "ke_recon-engine"
        }
      ],
      "sources": [
        "ke"
      ]
    },
    {
      "user": "recon_app",
      "db": "admin",
      "roles": [
        {
          "role": "readWrite",
          "db": "gh_betika_gh"
        }
      ],
      "sources": [
        "gh"
      ]
    },
    {
      "user": "root",
      "db": "admin",
      "roles": [
        {
          "role": "dbAdminAnyDatabase",
          "db": "admin"
        },
        {
          "role": "readWriteAnyDatabase",
          "db": "admin"
        },
        {
          "role": "userAdminAnyDatabase",
          "db": "admin"
        }
      ],
      "sources": [
        "ke"
      ]
    },
    {
      "user": "schema_auditor",
      "db": "admin",
      "roles": [
        {
          "role": "bmnSchemaAuditor",
          "db": "admin"
        },
        {
          "role": "oplogReader",
          "db": "admin"
        }
      ],
      "sources": [
        "cd",
        "gh",
        "ke",
        "mw",
        "tz",
        "ug"
      ]
    },
    {
      "user": "uxUser",
      "db": "admin",
      "roles": [
        {
          "role": "readWrite",
          "db": "ke_betika_favorites"
        }
      ],
      "sources": [
        "ke"
      ]
    },
    {
      "user": "reconciliation_app",
      "db": "cd_betika_cd",
      "roles": [
        {
          "role": "dbOwner",
          "db": "cd_betika_cd"
        }
      ],
      "sources": [
        "cd"
      ]
    },
    {
      "user": "uxUser",
      "db": "ke_betika_favorites",
      "roles": [
        {
          "role": "dbAdmin",
          "db": "ke_betika_favorites"
        },
        {
          "role": "readWrite",
          "db": "ke_betika_favorites"
        }
      ],
      "sources": [
        "ke"
      ]
    },
    {
      "user": "help_admin",
      "db": "ke_betika_help_center",
      "roles": [
        {
          "role": "dbAdmin",
          "db": "ke_betika_help_center"
        },
        {
          "role": "readWrite",
          "db": "ke_betika_help_center"
        },
        {
          "role": "userAdmin",
          "db": "ke_betika_help_center"
        }
      ],
      "sources": [
        "ke"
      ]
    },
    {
      "user": "recon-engine_app",
      "db": "ke_recon-engine",
      "roles": [
        {
          "role": "readWrite",
          "db": "ke_recon-engine"
        }
      ],
      "sources": [
        "ke"
      ]
    }
  ]
};

const APPLY = String(process.env.BMN_APPLY || '0') === '1';
const PHASE = String(process.env.BMN_PHASE || '').toLowerCase();
const ONLY_DB = String(process.env.BMN_DB || '');
const PHASES = ['collections', 'indexes', 'views', 'security', 'verify'];
const C = process.env.NO_COLOR
  ? { r: '', g: '', y: '', b: '', c: '', d: '', x: '' }
  : { r: '\x1b[31m', g: '\x1b[32m', y: '\x1b[33m', b: '\x1b[34m', c: '\x1b[36m', d: '\x1b[2m', x: '\x1b[0m' };

let errors = 0;
let warnings = 0;
const out = (color, tag, msg) => print(`${color}[${tag}]${C.x} ${msg}`);
const info = (m) => out(C.b, 'INFO', m);
const ok = (m) => out(C.g, ' OK ', m);
const planned = (m) => out(C.c, 'PLAN', m);
const skip = (m) => out(C.d, 'SKIP', m);
const warn = (m) => { warnings += 1; out(C.y, 'WARN', m); };
const fail = (m) => { errors += 1; out(C.r, 'FAIL', m); };

// Relaxed EJSON (dates, regex, ObjectId...) -> BSON-aware JS values.
const des = (v) => EJSON.deserialize({ v: v }, { relaxed: true }).v;
const inScope = (dbName) => !ONLY_DB || ONLY_DB === dbName;
const exists = (d, name) => d.getCollectionInfos({ name: name }, { nameOnly: true }).length > 0;
const js = (v) => JSON.stringify(v);

function run(d, cmd) {
  const res = d.runCommand(cmd);
  if (!res || res.ok !== 1) {
    throw new Error(js(res));
  }
  return res;
}

function phaseCollections() {
  for (const c of PLAN.collections) {
    if (!inScope(c.db)) continue;
    const ns = `${c.db}.${c.name}`;
    const d = db.getSiblingDB(c.db);
    try {
      if (exists(d, c.name)) {
        skip(`${ns} already exists`);
      } else if (!APPLY) {
        planned(`create ${ns} (${c.type}) options=${js(c.options)} ${C.d}<- ${c.source}${C.x}`);
      } else {
        run(d, Object.assign({ create: c.name }, des(c.options)));
        ok(`created ${ns}`);
      }
      if (c.shard_key) {
        if (!PLAN.target_sharded) {
          warn(`${ns}: source shard key ${js(c.shard_key)} not applied (target is not sharded)`);
        } else if (c.type === 'timeseries') {
          warn(`${ns}: time-series collection must be sharded manually (key ${js(c.shard_key)})`);
        } else if (!APPLY) {
          planned(`shardCollection ${ns} key=${js(c.shard_key)} unique=${c.shard_unique}`);
        } else {
          const admin = db.getSiblingDB('admin');
          try { admin.runCommand({ enableSharding: c.db }); } catch (e) { /* already enabled / not required (6.0+) */ }
          run(admin, { shardCollection: ns, key: des(c.shard_key), unique: !!c.shard_unique });
          ok(`sharded ${ns} on ${js(c.shard_key)}`);
        }
      }
    } catch (e) {
      fail(`${ns}: ${e.message}`);
    }
  }
}

function phaseIndexes() {
  for (const ix of PLAN.indexes) {
    if (!inScope(ix.db)) continue;
    const ns = `${ix.db}.${ix.collection}`;
    const d = db.getSiblingDB(ix.db);
    let existing = new Set();
    if (exists(d, ix.collection)) {
      existing = new Set(d.getCollection(ix.collection).getIndexes().map((i) => i.name));
    } else if (APPLY) {
      warn(`${ns} does not exist: run the collections phase and the data load first`);
      continue;
    }
    for (const spec of ix.specs) {
      if (existing.has(spec.name)) {
        skip(`${ns} index ${spec.name} already exists`);
        continue;
      }
      if (!APPLY) {
        planned(`createIndex ${ns} ${spec.name} ${js(spec)}`);
        continue;
      }
      try {
        run(d, { createIndexes: ix.collection, indexes: [des(spec)] });
        ok(`created index ${ns} ${spec.name}`);
      } catch (e) {
        fail(`${ns} index ${spec.name}: ${e.message}`);
      }
    }
  }
}

function phaseViews() {
  for (const v of PLAN.views) {
    if (!inScope(v.db)) continue;
    const ns = `${v.db}.${v.name}`;
    const d = db.getSiblingDB(v.db);
    try {
      if (exists(d, v.name)) {
        skip(`view ${ns} already exists`);
        continue;
      }
      const cmd = { create: v.name, viewOn: v.viewOn, pipeline: des(v.pipeline) };
      if (v.collation) cmd.collation = des(v.collation);
      if (!APPLY) {
        planned(`createView ${ns} on ${v.viewOn} pipeline=${js(v.pipeline)}`);
      } else {
        run(d, cmd);
        ok(`created view ${ns}`);
      }
    } catch (e) {
      fail(`view ${ns}: ${e.message}`);
    }
  }
}

function phaseSecurity() {
  for (const r of PLAN.roles) {
    if (!inScope(r.db)) continue;
    const d = db.getSiblingDB(r.db);
    try {
      if ((d.runCommand({ rolesInfo: r.role }).roles || []).length > 0) {
        skip(`role ${r.role}@${r.db} already exists`);
      } else if (!APPLY) {
        planned(`createRole ${r.role}@${r.db} roles=${js(r.roles)} privileges=${r.privileges.length}`);
      } else {
        run(d, { createRole: r.role, privileges: des(r.privileges), roles: r.roles });
        ok(`created role ${r.role}@${r.db}`);
      }
    } catch (e) {
      fail(`role ${r.role}@${r.db}: ${e.message}`);
    }
  }
  for (const u of PLAN.users) {
    if (!inScope(u.db)) continue;
    const d = db.getSiblingDB(u.db);
    try {
      if ((d.runCommand({ usersInfo: u.user }).users || []).length > 0) {
        skip(`user ${u.user}@${u.db} already exists`);
      } else if (!APPLY) {
        planned(`createUser ${u.user}@${u.db} roles=${js(u.roles)} ${C.d}<- ${u.sources.join(',')}${C.x}`);
      } else {
        print(`Password for ${u.user}@${u.db}:`);
        run(d, { createUser: u.user, pwd: passwordPrompt(), roles: u.roles });
        ok(`created user ${u.user}@${u.db}`);
      }
    } catch (e) {
      fail(`user ${u.user}@${u.db}: ${e.message}`);
    }
  }
}

function phaseVerify() {
  for (const c of PLAN.collections) {
    if (!inScope(c.db)) continue;
    const ns = `${c.db}.${c.name}`;
    const d = db.getSiblingDB(c.db);
    try {
      if (!exists(d, c.name)) {
        fail(`${ns} is missing on target`);
        continue;
      }
      if (c.type === 'timeseries') {
        const n = d.getCollection(c.name).countDocuments({});
        info(`${ns} (time-series) holds ${n} measurements; snapshot count is not comparable`);
        continue;
      }
      const n = d.getCollection(c.name).estimatedDocumentCount();
      if (n === c.expected_documents) {
        ok(`${ns} documents=${n}`);
      } else {
        warn(`${ns} documents=${n} expected=${c.expected_documents} (snapshot metadata; sources may have changed)`);
      }
    } catch (e) {
      fail(`${ns}: ${e.message}`);
    }
  }
}

if (!PHASES.includes(PHASE)) {
  print(`${C.r}Set BMN_PHASE to one of: ${PHASES.join(', ')}${C.x}`);
  quit(2);
}

info(`betika_mongodb_normalized bootstrap | phase=${PHASE} | mode=${APPLY ? 'APPLY' : 'DRY-RUN'}` +
  `${ONLY_DB ? ` | db=${ONLY_DB}` : ''} | plan target=${PLAN.target || 'undefined'}`);
({ collections: phaseCollections, indexes: phaseIndexes, views: phaseViews, security: phaseSecurity, verify: phaseVerify })[PHASE]();
info(`finished: errors=${errors} warnings=${warnings}`);
quit(errors > 0 ? 1 : 0);
