MONGOSHBINPATH=`which mongosh`
export MONGOADMINUSR="admin"
export MONGOADMINPAS="6UAvkhAwxm2gfF4BcGNWhEaIbRAZOr2C"
export ADMINDB="admin"
export MONGOHOST="gh-mongodbcluster/gh-mongodbcluster01.betika.private,gh-mongodbcluster02.betika.private,gh-mongodbcluster03.betika.private"
