MONGOSHBINPATH=`which mongosh`
export MONGOADMINUSR="admin"
export MONGOADMINPAS="6UAvkhAwxm2gfF4BcGNWhEaIbRAZOr2C"
export ADMINDB="admin"
export MONGOHOST="mw-mongodbcluster/mw-mongodbcluster01.betika.private,mw-mongodbcluster02.betika.private,mw-mongodbcluster03.betika.private"
