MONGOSHBINPATH=`which mongosh`
export MONGOADMINUSR="admin"
export MONGOADMINPAS="wirtAmLQtj5gxLG8CuG9igA0mIet4Cb6"
export ADMINDB="admin"
export MONGOHOST="tz-mongodbcluster01/tz-mongodbcluster01-node01.betika.private,tz-mongodbcluster01-node02.betika.private,tz-mongodbcluster01-node03.betika.private"
