#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -e
set -x

# --- Colors output variables ---

blk=$(tput blink)
bld=$(tput bold)             # Bold
red=${bld}$(tput setaf 1)    # Red
grn=${bld}$(tput setaf 2)    # Green
yel=${bld}$(tput setaf 3)    # Yellow
blu=${bld}$(tput setaf 4)    # Blue
mag=${bld}$(tput setaf 5)    # Purple
cyn=${bld}$(tput setaf 6)    # Cyan
wht=${bld}$(tput setaf 7)    # White
off=$(tput sgr0)             # Text reset

# --- Functions definition Definitions ---

# -- Log message function
function log_message(){

  LABEL=$2
  MESSAGE_HEAD_LINE="[`date +"%Y-%m-%d %H:%M:%S"`]${LABEL}"

  case "$3" in
    'OK' ) MESSAGE_TYPE="${grn}${MESSAGE_HEAD_LINE}[OK]"
                     MESSAGE_TYPE_LOG="${MESSAGE_HEAD_LINE}[OK]"
                  ;;
    'INFO' ) MESSAGE_TYPE="${blu}${MESSAGE_HEAD_LINE}[INFO]"
                     MESSAGE_TYPE_LOG="${MESSAGE_HEAD_LINE}[INFO]"
                  ;;
    'ERROR' ) MESSAGE_TYPE="${red}${MESSAGE_HEAD_LINE}[ERROR]"
                            MESSAGE_TYPE_LOG="${MESSAGE_HEAD_LINE}[ERROR]"
                  ;;
    'WARNING' ) MESSAGE_TYPE="${yel}${MESSAGE_HEAD_LINE}[WARN]"
                                  MESSAGE_TYPE_LOG="${MESSAGE_HEAD_LINE}[WARN]"
                  ;;  
  esac

  case "$1" in
    'STANDARD' ) MESSAGE_HEAD="${MESSAGE_TYPE}"
                  ;;
    'LOG' ) MESSAGE_HEAD="${MESSAGE_TYPE_LOG}"
                  ;;
  esac
  MSG=$4

  #MESSAGE_HEAD="${MESSAGE_TYPE}"
  echo "${MESSAGE_HEAD} ${MSG} ${off}"
}

# --- Helper Function to Generate Secure Passwords ---
# Uses openssl for cryptographically strong random data.
# $1: The length of the random bytes to generate (32 bytes = 44 base64 chars)
generate_password() {
    openssl rand -base64 "${1:-16}"
}

mongoadminroles_bootstrap(){
  # declare -a arr=("${@}")
  JSADMINROLESPATH=$1
  # adminuser=${arr[1]}
  # adminuserpwd="${arr[4]}"
  # clusteradminusr=${arr[2]}
  # clusteradminusrpwd="${arr[5]}"
  # bkpuser=${arr[3]}
  # bkpuserpwd="${arr[6]}"
  cat <<EOF > "${JSADMINROLESPATH}"
/* =============================================================================================
 *   WARNING: This JS script file has been automatically generated by an automation script. 
 *          Please, note that any manual changes may be lost.
 *  
 *  > Auto-generated for bootstrapping MongoDB main basic admin users -> ROLES CREATION
 * =============================================================================================
*/

db.createRole(
{
    "role": "explainRole",
    "privileges": [
      {
        "resource": { "db": "", "collection": ""
      },
        "actions":["collStats","dbHash","dbStats","find", "listIndexes","listCollections"]
      },
      {
        "resource": { "db": "", "collection": "system.version"  },
      "actions": [ "find" ]
      }
    ],
    "roles": []
  }
)

db.createRole(
{ 
  "role": "pbmAnyAction",
  "privileges": [
    { 
      "resource": { "anyResource": true },
      "actions": [ "anyAction" ]
    }],
    "roles": []
});
EOF
}

#print("✅ Successfully created admin, clusterAdmin, and pbmuser.");

mongoadminusers_bootstrap(){
  declare -a arr=("${@}")
  JSADMINUSERSPATH=${arr[0]}
  ADMINUSER="${arr[1]}"
  CLUSTERADMINUSER="${arr[2]}"
  BKPUSER="${arr[3]}"
  ADMINUSERPWD="${arr[4]}"
  CLUSTERADMINPWD="${arr[5]}"
  BKPPWD="${arr[6]}"
  cat <<EOF > "${JSADMINUSERSPATH}"
/* =============================================================================================
 *   WARNING: This JS script file has been automatically generated by an automation script. 
 *          Please, note that any manual changes may be lost.
 *  
 *  > Auto-generated for bootstrapping MongoDB main basic admin users -> USERS CREATION
 * =============================================================================================
*/

// Create the main administrative user
db.createUser({
  user: "${ADMINUSER}",
  pwd: "${ADMINUSERPWD}",
  roles: [ { role: "root", db: "admin" } ]
});
db.auth("${ADMINUSER}","${ADMINUSERPWD}");

// Create the cluster administrator user (for managing the replica set)
db.createUser({
  user: "${CLUSTERADMINUSER}",
  pwd: "${CLUSTERADMINPWD}",
  roles: [ { role: "clusterAdmin", db: "admin" } ]
});

// Create the user for Percona Backup for MongoDB
db.createUser({
  user: "${BKPUSER}",
  pwd: "${BKPPWD}",
  roles: [
      { role : "backup", db: "admin" },
      { role : "clusterAdmin", db: "admin" },
      { role : "clusterMonitor", db: "admin"},
      { role : "readWriteAnyDatabase", db: "admin" },
      { role : "userAdminAnyDatabase", db: "admin" },
      { role : "restore", db: "admin" }
  ]
});

EOF
}
# print("✅ Successfully created admin, clusterAdmin, and pbmuser.");

mongoadminuser_check(){
  declare -a arr=("${@}")
  jspathfile=${arr[0]}
  usertocheck=${arr[1]}
  cat <<EOF > "${jspathfile}"
db.system.users.find({ user: "${usertocheck}" })
EOF
}

# -----------------------------------------------------------------------------

# --- Configuration ---
MONGOSHBINPATH=`which mongosh`
MONGO_CONF_DIR="/etc/mongod"
JS_FILE="${MONGO_CONF_DIR}/.mongo-users.js"
ROLES_JS_FILE="${MONGO_CONF_DIR}/.mongo-roles.js"
ADMIN_USER="mongoAdmin"
CLUSTER_ADMIN_USER="clusterAdmin"
BACKUP_USER="pbmuser"
MONGODB="admin"
MONGOAUTHDB="admin"
JSCHECK1="/tmp/${ADMIN_USER}.js"
JSCHECK2="/tmp/${CLUSTER_ADMIN_USER}.js"
JSCHECK3="/tmp/${BACKUP_USER}.js"
ERRORCODE=0
OUTPUT_CONN_FILE="${MONGO_CONF_DIR}/.mongo.conn"
# --- Main Script Logic ---
#echo "🚀 Starting MongoDB user bootstrapping..."
MSG=`log_message "STANDARD" "[MONGODB][BOOTSTRAP]" "INFO" "🚀 Starting MongoDB user bootstrapping..."`
echo "${MSG}"

# 1. Generate passwords for each user and users creation
#echo "🔑 Generating user Roles JS script..."
MSG=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][ROLES][CREATION][JS]" "INFO" "📝 Creating user roles creation script at ${ROLES_JS_FILE}..."`
echo "${MSG}"
#arraycred=( ${ROLES_JS_FILE} ${ADMIN_USER} ${CLUSTER_ADMIN_USER} ${BACKUP_USER} ${ADMIN_PASSWORD} ${CLUSTER_ADMIN_PASSWORD} ${BACKUP_USER_PASSWORD} )
mongoadminroles_bootstrap "${ROLES_JS_FILE}"
if [[ -e ${ROLES_JS_FILE} ]]; then
  # JS configuration file should not be empty
  if [[ ! -s ${ROLES_JS_FILE} ]]; then
    ERRORMSG=`log_message "STANDARD" "[BOOTSTRAP][ADMIN_USERS][ROLES][CREATION][JS][EMPTY]" "ERROR" " Admin User Roles ${ROLES_JS_FILE} File Not Created!!!!"`
    echo "${ERRORMSG}"
    ERRORCODE=-10
  else
    MSG=`log_message "STANDARD" "[BOOTSTRAP][ADMIN_USERS][ROLES][CREATION][JS]" "OK" "Admin User Roles ${ROLES_JS_FILE} File Created!! "`
    echo ${MSG}
    OUTPUTCLI="mongosh --file ${ROLES_JS_FILE}"
    RUNMSG=`log_message "STANDARD" "[BOOTSTRAP][ADMIN_USERS][ROLES][CREATION][JS][RUN]" "INFO" " Running JS script against mongo: ${OUTPUTCLI} "`
    echo "${RUNMSG}"
  fi
fi


#echo "🔑 Generating secure passwords..."
MSG=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREDENTIALS][CREATION]" "INFO" "🔑 Generating secure passwords for main administrative users : ${ADMIN_USER}, ${CLUSTER_ADMIN_USER} and ${BACKUP_USER}"`
echo "${MSG}"
ADMIN_PASSWORD=$(generate_password)
CLUSTER_ADMIN_PASSWORD=$(generate_password)
BACKUP_USER_PASSWORD=$(generate_password)
arraycred=( ${JS_FILE} ${ADMIN_USER} ${CLUSTER_ADMIN_USER} ${BACKUP_USER} ${ADMIN_PASSWORD} ${CLUSTER_ADMIN_PASSWORD} ${BACKUP_USER_PASSWORD} )
# 2. Create the JavaScript file for mongosh
MSG=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][JS]" "INFO" "📝 Creating user creation script at ${JS_FILE}..."`
echo "${MSG}"
mongoadminusers_bootstrap ${arraycred[@]}

# 3. Execute the script against the MongoDB instance
# This assumes mongod is running locally and without authentication initially.
# The server will be secured once the first user (admin) is created.
# echo "⚙️ Executing script against MongoDB..."
if [[ -e ${JS_FILE} ]]; then
  # JS configuration file should not be empty
  if [[ ! -s ${JS_FILE} ]]; then
    ERRORMSG=`log_message "STANDARD" "[BOOTSTRAP][ADMIN_USERS][CREATION][JS][EMPTY]" "ERROR" " Admin Users ${JS_FILE} File Not Created!!!!"`
    echo "${ERRORMSG}"
    ERRORCODE=-11
  else
    MSG=`log_message "STANDARD" "[BOOTSTRAP][ADMIN_USERS][CREATION][JS]" "OK" "Admin Users ${JS_FILE} File Created!! "`
    echo ${MSG}
    OUTPUTCLI="mongosh --file ${JS_FILE}"
    RUNMSG=`log_message "STANDARD" "[BOOTSTRAP][ADMIN_USERS][CREATION][JS][RUN]" "INFO" "Running JS script against mongo: ${OUTPUTCLI} "`
    echo "${RUNMSG}"
  fi
fi
MSG=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][JS][RUN]" "INFO" "📝 Executing ${JS_FILE} script against MongoDB for creating users and credentials..."`
echo "${MSG}"
${MONGOSHBINPATH} --file "${JS_FILE}" ${MONGODB}
if [[ $? -eq 0 ]]; then
  MSG=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][JS][RUN]" "OK" "📝 ${JS_FILE} script Executed"`
  echo "${MSG}"
  MSG=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][VERIFICATION]" "INFO" "📝 Starting users verification checks..."`
  echo "${MSG}"

  # Users verification check
  MSG=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][VERIFICATION]" "INFO" "📝 Checking ${ADMIN_USER} user and credentails..."`
  echo "${MSG}"
  arrayusrcheck1=( ${JSCHECK1} ${ADMIN_USER} )
  mongoadminuser_check ${arrayusrcheck1[@]}
  ${MONGOSHBINPATH} --file ${JSCHECK1} --authenticationDatabase ${MONGOAUTHDB} -u ${ADMIN_USER} -p ${ADMIN_PASSWORD} ${MONGODB}
  if [[ $? -eq 0 ]]; then
    MSGVEROK=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][VERIFICATION]" "OK" "✅ ${ADMIN_USER} verified!!"`
    echo "${MSGVEROK}"
  else
    ERRORCODE=1
  fi

  # Admin users check verification
  arrayusrcheck2=( ${JSCHECK2} ${CLUSTER_ADMIN_USER} )
  mongoadminuser_check ${arrayusrcheck2[@]}
  ${MONGOSHBINPATH} --file ${JSCHECK2} --authenticationDatabase ${MONGOAUTHDB} -u ${ADMIN_USER} -p ${ADMIN_PASSWORD} ${MONGODB}
  if [[ $? -eq 0 ]]; then
    MSGVEROK=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][VERIFICATION]" "OK" "✅ ${CLUSTER_ADMIN_USER} verified!!"`
    echo "${MSGVEROK}"
  else
    ERRORCODE=2
  fi
  
  arrayusrcheck3=( ${JSCHECK3} ${BACKUP_USER} )
  mongoadminuser_check ${arrayusrcheck3[@]}
  ${MONGOSHBINPATH} --file ${JSCHECK3} --authenticationDatabase ${MONGOAUTHDB} -u ${ADMIN_USER} -p ${ADMIN_PASSWORD} ${MONGODB}
  if [[ $? -eq 0 ]]; then
    MSGVEROK=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][VERIFICATION]" "OK" "✅ ${BACKUP_USER} verified!!"`
    echo "${MSGVEROK}"
    echo "${ADMIN_USER}|${ADMIN_PASSWORD}|${MONGODB}" > ${OUTPUT_CONN_FILE}
    echo "${CLUSTER_ADMIN_USER}|${CLUSTER_ADMIN_PASSWORD}|${MONGODB}" >> ${OUTPUT_CONN_FILE}
    echo "${BACKUP_USER}|${BACKUP_USER_PASSWORD}|${MONGODB}" >> ${OUTPUT_CONN_FILE}
  else
    ERRORCODE=3
  fi


fi

# 4. Clean up the temporary JavaScript file
# This is a critical security step to avoid leaving passwords on disk.
# echo "🧹 Cleaning up temporary password file..."
# rm -f "${JS_FILE}"

# 5. Output the generated passwords for storage in a secret manager
# In a real-world scenario, you would pipe this to Vault, GCP/AWS Secret Manager, etc.
# echo "🎉 Bootstrapping complete! Store these passwords securely:"
if [[ ${ERRORCODE} -eq 0 ]]; then
  #statements
  MSG=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][JS][RUN]" "OK" "📝 🎉 Bootstrapping complete! Store these passwords securely:"`
  echo "${MSG}"
  # echo "========================================================"
  MSG1=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][user=${ADMIN_USER}]" "[INFO]" "📝 🎉 Bootstrapping complete! Store these passwords securely:"`
  MSG2=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][user=${ADMIN_USER}]" "[INFO]" "📝 Admin User:         ${ADMIN_USER}"`
  MSG3=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][user=${ADMIN_USER}]" "[INFO]" "📝 Admin Password:     ${ADMIN_PASSWORD}"`
  # echo "Admin User:         ${ADMIN_USER}"
  # echo "Admin Password:     ${ADMIN_PASSWORD}"
  MSG4=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][user=${CLUSTER_ADMIN_USER}]" "[INFO]" "📝 Cluster Admin User: ${CLUSTER_ADMIN_USER}"`
  MSG5=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][user=${CLUSTER_ADMIN_PASSWORD}]" "[INFO]" "📝 Cluster Password:   ${CLUSTER_ADMIN_PASSWORD}"`
  # echo "--------------------------------------------------------"
  # echo "Cluster Admin User: ${CLUSTER_ADMIN_USER}"
  # echo "Cluster Password:   ${CLUSTER_ADMIN_PASSWORD}"
  # echo "--------------------------------------------------------"
  MSG6=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][user=${BACKUP_USER}]" "[INFO]" "📝 Backup User:        ${BACKUP_USER}"`
  MSG7=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION][user=${BACKUP_USER}]" "[INFO]" "📝 Backup Password:    ${BACKUP_USER_PASSWORD}"`
  echo "${MSG1}"
  echo "${MSG2}"
  echo "${MSG3}"
  echo "${MSG4}"
  echo "${MSG5}"
  echo "${MSG6}"
  echo "${MSG7}"

else
  ERRMSG=`log_message "STANDARD" "[MONGODB][BOOTSTRAP][ADMIN_USERS][CREATION]" "ERROR" "📝 🎉 Bootstrapping failed!!"`
fi
# echo "Backup User:        ${BACKUP_USER}"
# echo "Backup Password:    ${BACKUP_USER_PASSWORD}"
# echo "========================================================"