# ===================================================================
# File: startup-script.sh
# Description: CentOS-specific startup script with advanced configuration for MongoDB 8.
# ===================================================================

#!/bin/bash
set -e
#set -x

# --- Colors output variables ---

blk=$(tput blink)
bld=$(tput bold)             # Bold
red=${bld}$(tput setaf 1)    # Red
grn=${bld}$(tput setaf 2)    # Green
yel=${bld}$(tput setaf 3)    # Yellow
blu=${bld}$(tput setaf 4)    # Blue
mag=${bld}$(tput setaf 5)    # Purple
cyn=${bld}$(tput setaf 6)    # Cyan
wht=${bld}$(tput setaf 7)    # White
off=$(tput sgr0)             # Text reset

# --- Functions definition Definitions ---
# -- Help/Error input parameters ouput function
function help_msg (){
  echo -e " Usage command line    : ${0} [ primary | secondary ] . Default value : secondary"
  echo -e " Example with no param : ${0} "
  echo -e " Example for primary   : ${0} primary"
  echo -e " Example for primary   : ${0} secondary"
}

# -- Log message function
function log_message(){

  LABEL=$2
  MESSAGE_HEAD_LINE="[`date +"%Y-%m-%d %H:%M:%S"`]${LABEL}"

  case "$3" in
    'OK' ) MESSAGE_TYPE="${grn}${MESSAGE_HEAD_LINE}[OK]"
                     MESSAGE_TYPE_LOG="${MESSAGE_HEAD_LINE}[OK]"
                  ;;
    'INFO' ) MESSAGE_TYPE="${blu}${MESSAGE_HEAD_LINE}[INFO]"
                     MESSAGE_TYPE_LOG="${MESSAGE_HEAD_LINE}[INFO]"
                  ;;
    'ERROR' ) MESSAGE_TYPE="${red}${MESSAGE_HEAD_LINE}[ERROR]"
                            MESSAGE_TYPE_LOG="${MESSAGE_HEAD_LINE}[ERROR]"
                  ;;
    'WARNING' ) MESSAGE_TYPE="${yel}${MESSAGE_HEAD_LINE}[WARN]"
                                  MESSAGE_TYPE_LOG="${MESSAGE_HEAD_LINE}[WARN]"
                  ;;  
  esac

  case "$1" in
    'STANDARD' ) MESSAGE_HEAD="${MESSAGE_TYPE}"
                  ;;
    'LOG' ) MESSAGE_HEAD="${MESSAGE_TYPE_LOG}"
                  ;;
  esac
  MSG=$4

  #MESSAGE_HEAD="${MESSAGE_TYPE}"
  echo "${MESSAGE_HEAD} ${MSG} ${off}"
}

# --- Function for generating Transparent Huge Pages service disabling
function thp_service_disable(){
  cat <<EOF > $1
# =============================================================================================
#  WARNING: This service file has been automatically generated by an automation script. 
#           Please, note that any manual changes may be lost.
# =============================================================================================
# 
# $1
#

[Unit]
Description=Disable Transparent Huge Pages (THP)
DefaultDependencies=no
After=sysinit.target local-fs.target
Before=mongod.service

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'echo never | tee /sys/kernel/mm/transparent_hugepage/enabled > /dev/null'
ExecStart=/bin/sh -c 'echo never | tee /sys/kernel/mm/transparent_hugepage/defrag > /dev/null'

[Install]
WantedBy=multi-user.target
EOF
}

# --- Function for generating Transparent Huge Pages service disabling
function thp_service_enable(){
  cat <<EOF > $1
# =============================================================================================
#  WARNING: This service file has been automatically generated by an automation script. 
#           Please, note that any manual changes may be lost.
# =============================================================================================
# 
# $1
#

[Unit]
Description=Enable Transparent Hugepages (THP)
DefaultDependencies=no
After=sysinit.target local-fs.target
Before=mongod.service

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'echo always | tee /sys/kernel/mm/transparent_hugepage/enabled > /dev/null && echo defer+madvise | tee /sys/kernel/mm/transparent_hugepage/defrag > /dev/null && echo 0 | tee /sys/kernel/mm/transparent_hugepage/khugepaged/max_ptes_none > /dev/null && echo 1 | tee /proc/sys/vm/overcommit_memory > /dev/null'

[Install]
WantedBy=basic.target
EOF
}

# --- Function for generating Mongodb service
# -- * $1 : mongod file full path name
function mongod_service_file(){
cat <<EOF > $1
# =============================================================================================
#  WARNING: This service file has been automatically generated by an automation script. 
#           Please, note that any manual changes may be lost.
# =============================================================================================
# 
# $1
#

[Unit]
Description=High-performance, schema-free document-oriented database
After=time-sync.target network.target

[Service]
User=mongod
Group=mongod
PermissionsStartOnly=true
LimitFSIZE=infinity
LimitCPU=infinity
LimitAS=infinity
LimitNOFILE=64000
LimitNPROC=64000
EnvironmentFile=-/etc/sysconfig/mongod
Environment="GLIBC_TUNABLES=glibc.pthread.rseq=0"
Environment="MONGODB_CONFIG_OVERRIDE_NOFORK=1"
ExecStartPre=/usr/bin/percona-server-mongodb-helper.sh
ExecStart=/usr/bin/env bash -c "\${NUMACTL} /usr/bin/mongod \${OPTIONS}"

[Install]
WantedBy=multi-user.target
EOF
}

# --- Function for mongod secure ulimits setup
function mongod_sec_ulimits(){
  cat <<EOF > $1
# =============================================================================================
#  WARNING: This configuration file has been automatically generated by an automation script. 
#           Please, note that any manual changes may be lost.
# =============================================================================================

# Recommended security limits for MongoDB
mongod   soft   nofile   64000
mongod   hard   nofile   64000
mongod   soft   nproc    64000
mongod   hard   nproc    64000
EOF
}

# --- Function for mongod.conf file rewrite
# -- Paramaters info :
# -- * $1 - arr[0] : mongod.conf file full path name
# -- * $2 - arr[1] : mongodb service full db data dir path name
# -- * $3 - arr[2] : wiredTiger engine cache size in GB -> equivalent to mysql innodb_buffer_pool_size
# -- * $4 - arr[3] : mongod output log file path name
# -- * $5 - arr[4] : mongod pid file path name
# -- * $6 - arr[5] : authorization keyFile full path name
# -- * $7 - arr[6] : replicaSet Name
function mongod_confile_rewrite(){
  declare -a arr=("${@}")
  MONGODCONFPATH=${arr[0]}
  MONGODBPATH=${arr[1]}
  MONGODWIREDSIZE=${arr[2]}
  MONGODLOGPATH=${arr[3]}
  MONGODPIDPATH=${arr[4]}
  MONGODKEYPATH=${arr[5]}
  MONGODRSNAME=${arr[6]}
  cat <<EOF > ${MONGODCONFPATH}
# =============================================================================================
#  WARNING: This configuration file has been automatically generated by an automation script. 
#           Please, note that any manual changes may be lost.
# =============================================================================================
#
# mongod.conf

# For documentation of all options, see:
#   https://docs.percona.com/percona-server-for-mongodb/8.0/reference/configuration-options.html

# Where and how to store data.
storage:
  dbPath: ${MONGODBPATH}
  directoryPerDB: true
  journal:
    enabled: true
  engine: wiredTiger
  wiredTiger:
    engineConfig:
      # Set cache size to 1GB. A good starting point for a 16GB RAM VM (e2-standard-4).
      # Formula: (RAM - 1GB) * 0.5. Here, (16-1)*0.5 = 7.5. We use 1GB as a safe value.
      cacheSizeGB: ${MONGODWIREDSIZE}
      checkpointSizeMB: 1000
#      statisticsLogDelaySecs: 0
#      journalCompressor: snappy
#      directoryForIndexes: false
#    collectionConfig:
#      blockCompressor: snappy
#    indexConfig:
#      prefixCompression: true

#  More info for inMemory: https://www.percona.com/doc/percona-server-for-mongodb/4.4/inmemory.html#configuring-percona-memory-engine
#  inMemory:
#    engineConfig:
#      inMemorySizeGB: 1
#      statisticsLogDelaySecs: 0

# Two options below can be used for wiredTiger and inMemory storage engines
#setParameter:
#    wiredTigerConcurrentReadTransactions: 128
#    wiredTigerConcurrentWriteTransactions: 128

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: ${MONGODLOGPATH}
  logRotate: reopen 

# network interfaces
net:
  port: 27017
  bindIp: 0.0.0.0

# process management
processManagement:
  pidFilePath: ${MONGODPIDPATH}

# security
security:
  authorization: "enabled"
#  keyFile: ${MONGODKEYPATH}


# replication
#replication:
#  replSetName: "${MONGODRSNAME}"

# profiling
# UPDATED: The 'mode' parameter is deprecated in MongoDB 6.0+
# This sets the threshold for logging slow operations.
operationProfiling:
  mode: slowOp
  slowOpThresholdMs: 100

#sharding:

## Enterprise-Only Options:

#auditLog:

#snmp:
EOF
}

# mongod logrotate configuration
# -- Paramaters info :
# -- * $1 - arr[0] : logrotate configuration file path for mongod
# -- * $2 - arr[1] : mongod log file to rotate
# -- * $3 - arr[2] : mongod pid file
function mongod_logrotate_setup() {
  declare -a arr=("${@}")
  logrotateconfpathfile=${arr[0]}
  mongologpathfile=${arr[1]}
  mongopidpathfile=${arr[2]}
  cat <<EOF > ${logrotateconfpathfile}
# =============================================================================================
#  WARNING: This configuration file has been automatically generated by an automation script. 
#           Please, note that any manual changes may be lost.
# =============================================================================================
#
# ${logrotateconfpathfile}
${mongologpathfile} {
  daily
  size 300M
  rotate 10
  missingok
  compress
  delaycompress
  notifempty
  create 640 mongod mongod
  sharedscripts
  postrotate
    /bin/kill -SIGUSR1 \`cat ${mongopidpathfile} 2>/dev/null\` >/dev/null 2>&1
  endscript
}
EOF
}


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Main 
# --- Variable Definitions ---
EXITCODE=0
DATA_DISK_DEVICE="/dev/sdb"
INSTALLBKPDIR="/data/backup"
BASE_DIR="/data"
LOGROTATE_ROOT_DIR="/etc/logrotate.d"

MONGO_CONF_DIR="/etc/mongod"
MONGO_DATA_DIR="${BASE_DIR}/mongo"
MONGO_LOG_DIR="${BASE_DIR}/log/mongod"
MONGO_LOG_FILE_PATH="${MONGO_LOG_DIR}/mongod.log"
MONGO_PID_DIR="/var/run/mongodb"
MONGO_PID_FILE_PATH="${MONGO_PID_DIR}/mongod.pid"
MONGO_CNF_PATH="${MONGO_CONF_DIR}/mongod.conf"
MONGO_RS_KEYFILE_PATH="${MONGO_CONF_DIR}/mongodb.key"
MONGO_SERVICE_PATH="/usr/lib/systemd/system/mongod.service"
MONGOD_SECULIMITS_PATH="/etc/security/limits.d/20-mongodb.conf"
MONGOD_LOGROTATE_CNF="${LOGROTATE_ROOT_DIR}/mongod"
#MONGODB_NODE_REGEX="s/^([a-z]+)-([a-z]+)mongodb([0-9]+)-node([0-9]+)$/"
MONGODB_NODE_REGEX="s/^([a-z]+)-mongodbcluster([0-9]+)-node([0-9]+)$/"
PERCONA_HELPER_PATH="/usr/bin/percona-server-mongodb-helper.sh"
THP_ENABLE_SERVICE_PATH="/etc/systemd/system/enable-transparent-huge-pages.service"
THP_DISABLE_SERVICE_PATH="/etc/systemd/system/disable-thp.service"

MONGOD_DEF_CNF_FILE="/etc/mongod.conf"   # Default mongod configuration file

# Backup dirs
BKPSUFFIXNAME=`date +"%Y%m%d_%H%M%S"`
BKPBASEDIR="${BASE_DIR}/backup/install"
BKPINSTALLDIR="${BASE_DIR}/backup/install/${BKPSUFFIXNAME}"
mkdir -p ${BKPINSTALLDIR}

if [[ ! -d ${MONGO_CONF_DIR} ]]; then
  mkdir -p ${MONGO_CONF_DIR}
fi

# Wait for services to be ready
sleep 5

# Input parameters check and verification
if [[ $# -eq 0 ]]; then
   MSG=`log_message "STANDARD" "[PARAMETERS]" "WARNING" "MongoDB Role no provided. Setting default no: Node will be defined as secondary !!"`
   echo "${MSG}"
   role="secondary"
   else
	   role=${1}
fi

case "$role" in
  "primary") MSG=`log_message "STANDARD" "[PARAMETERS]" "INFO" "MongoDB Role will be set as PRIMARY !!"`
             is_primary="yes"
    ;;
  "secondary") MSG=`log_message "STANDARD" "[PARAMETERS]" "INFO" "MongoDB Role will be set as SECONDARY !!"`
             is_primary="no"
    ;;
  *) MSG=`log_message "STANDARD" "[PARAMETERS]" "ERROR" "MondoDB Node Role value : ${is_primary} is not a valid one!! Setting default as SECONDARY"`
     is_primary="no"
    ;;
esac

echo "${MSG}"

# --- Disk Formatting and Mounting ---
# ---
MSG=`log_message "STANDARD" "[DISK]" "INFO" "Formatting ${DATA_DISK_DEVICE} and create ${BASE_DIR} mount point..."`
echo "${MSG}"
MSG=`log_message "STANDARD" "[DISK][FORMAT]" "INFO" "Checking ${DATA_DISK_DEVICE} device block information."`
echo "${MSG}"
if ! blkid ${DATA_DISK_DEVICE}; then
  MSG=`log_message "STANDARD" "[DISK][FORMAT]" "INFO" "No block information for device ${DATA_DISK_DEVICE}. Formatting device... "`
  echo "${MSG}"
  mkfs.ext4 ${DATA_DISK_DEVICE}

  MSG=`log_message "STANDARD" "[DISK][MOUNT_POINT]" "INFO" "Mounting Point creation for ${DATA_DISK_DEVICE} in ${BASE_DIR}."`
  echo "${MSG}"
  mkdir -p ${BASE_DIR}
  if [[ $? -eq 0 ]]; then
    MSG=`log_message "STANDARD" "[DISK][MOUNT_POINT][OK]" "OK" "Mounting Point dir ${BASE_DIR} created!!"`
    echo "${MSG}"
  fi
  # mount -o discard,defaults ${DATA_DISK_DEVICE} ${BASE_DIR}
  MSG=`log_message "STANDARD" "[DISK][MOUNT]" "INFO" "Device mount setup in fstab"`
  echo "${MSG}"
  echo "${DATA_DISK_DEVICE}               ${BASE_DIR}    ext4     defaults        0 0" >> /etc/fstab
  MSG=`log_message "STANDARD" "[DISK][MOUNT]" "INFO" "Device mounting..."`
  echo "${MSG}"
  mount -a
  if [[ $? -eq 0 ]]; then
    MSG=`log_message "STANDARD" "[DISK][MOUNT][OK]" "OK" "${DATA_DISK_DEVICE} successfully mounted in ${BASE_DIR} !!"`
    echo "${MSG}"
    lsblk
  fi
else
  MSG=`log_message "STANDARD" "[DISK][FORMAT]" "INFO" "Device ${DATA_DISK_DEVICE} Formated. Device formating NOT REQUIRED!! "`
  echo "${MSG}"
fi


# --- Saltstack repo disabling ---
# MSG=`log_message "STANDARD" "[REPOS]" "INFO" "Disabling salt-py3-latest repo !!"`
# echo "${MSG}"
# sed -i 's/enabled=1/enabled=0/g' /etc/yum.repos.d/salt-py3-latest.repo

# --- bc command installing ---
dnf install -y bc

# --- Create MongoDB Directories ---
MSG=`log_message "STANDARD" "[MONGO_WORK_DIRS]" "INFO" "Creating custom directories for data, logs, and pids..."`
echo "${MSG}"
mkdir -p ${MONGO_DATA_DIR}
if [[ $? -eq 0 ]]; then
  MSGOK=`log_message "STANDARD" "[MONGO_WORK_DIRS]" "OK" "MongoDB Data Directory created -> ${MONGO_DATA_DIR}"`
  echo "${MSGOK}"
fi
mkdir -p ${MONGO_LOG_DIR}
if [[ $? -eq 0 ]]; then
  MSGOK=`log_message "STANDARD" "[MONGO_WORK_DIRS]" "OK" "MongoDB Log Directory created -> ${MONGO_LOG_DIR}"`
  echo "${MSGOK}"
fi
mkdir -p ${MONGO_PID_DIR}
if [[ $? -eq 0 ]]; then
  MSGOK=`log_message "STANDARD" "[MONGO_WORK_DIRS]" "OK" "MongoDB pid run created -> ${MONGO_PID_DIR}"`
  echo "${MSGOK}"
fi

# --- OS Performance Tuning (Percona Recommendations) ---
MSG=`log_message "STANDARD" "[OS_PERFORMANCE_SETUP]" "INFO" "Applying OS performance tuning settings..."`
echo "${MSG}"

MSG=`log_message "STANDARD" "[OS_PERFORMANCE_SETUP][THP]" "INFO" "Enabling Transparent Huge Pages (THP)"`
echo "${MSG}"
# 1. Disable Transparent Huge Pages (THP)
if [ ! -e ${THP_ENABLE_SERVICE_PATH} ]; then
  MSG=`log_message "STANDARD" "[OS_PERFORMANCE_SETUP][THP]" "INFO" "${THP_ENABLE_SERVICE_PATH} Not found! Creating File from the scratch"`
  echo "${MSG}"
  thp_service_enable "${THP_ENABLE_SERVICE_PATH}"
  MSG=`log_message "STANDARD" "[OS_PERFORMANCE_SETUP][THP][SERVICE]" "INFO" "THP service reload and enabling"`
  echo "${MSG}"
  systemctl daemon-reload
  systemctl enable --now disable-thp.service
  if [[ $? -eq 0 ]]; then
    MSG=`log_message "STANDARD" "[OS_PERFORMANCE_SETUP][THP][SERVICE]" "OK" "THP service enabled"`
    echo "${MSG}"
  fi
else
  MSG=`log_message "STANDARD" "[OS_PERFORMANCE_SETUP][THP]" "WARNING" "${THP_ENABLE_SERVICE_PATH} Found! Check if setup ok for Transparent Huge Pages (THP) Disabling"`
  echo "${MSG}"
fi

MSG=`log_message "STANDARD" "[OS_PERFORMANCE][SETUP][ULIMITS]" "INFO" "Checking recommended ulimits for the mongod user"`
echo "${MSG}"
if [[ -e ${MONGOD_SECULIMITS_PATH} ]]; then
  MSG=`log_message "STANDARD" "[OS_PERFORMANCE][SETUP][ULIMITS]" "WARNING" "ulimits for the mongod user already set up. Nothing to do"`
else
  MSG=`log_message "STANDARD" "[OS_PERFORMANCE][SETUP][ULIMITS]" "INFO" "Setting up recommended ulimits for the mongod user"`
  echo "${MSG}"
  # 2. Set recommended ulimits for the mongod user
  mongod_sec_ulimits "${MONGOD_SECULIMITS_PATH}"
fi

# --- Install Percona Server for MongoDB ---

# -- Repositories Enabling for PSMDB, PBM and PMM
MSG=`log_message "STANDARD" "[PERCONA][REPOS]" "INFO" "Preparing Percona Repositories"`
echo "${MSG}"
MSG=`log_message "STANDARD" "[PERCONA][REPOS][PERCONA_RELEASE][INSTALL]" "INFO" "Percona Release for Repositories and Packages Management Installation"`
echo "${MSG}"

dnf install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm
# PSMDB v8
MSG=`log_message "STANDARD" "[PERCONA][REPOS][PERCONA_RELEASE][ENABLE]" "INFO" "MongoDB and Percona Backup for MongoDB v8 Repositories Enabling"`
echo "${MSG}"
percona-release enable psmdb-80 release
# PBM
percona-release enable pbm release
# PMM client
MSG=`log_message "STANDARD" "[PERCONA][REPOS][PERCONA_RELEASE][PMM][ENABLE]" "INFO" "Percona Management ans Monitoring Client Enabling"`
echo "${MSG}"
percona-release enable pmm2-client

# -- Packages Install for : PSMDB, PBM and PMM
# PSMDB v8
MSG=`log_message "STANDARD" "[PERCONA][PERCONA_RELEASE][PSMDB8][INSTALL]" "INFO" "Installing Percona Server for MongoDB 8.0..."`
echo "${MSG}"
dnf install -y percona-server-mongodb 
# PBM
MSG=`log_message "STANDARD" "[PERCONA][PERCONA_RELEASE][PBM][INSTALL]" "INFO" "Installing Percona Backup for MongoDB 8.0..."`
echo "${MSG}"
dnf install -y percona-backup-mongodb
# PMM Client
MSG=`log_message "STANDARD" "[PERCONA][PERCONA_RELEASE][PMM][INSTALL]" "INFO" "Installing Percona Management ans Monitoring Client..."`
echo "${MSG}"
dnf install -y pmm2-client

# --- PSMDB installs /usr/bin/percona-server-mongodb-helper.sh script
# Before going forward, we need tunning it for registering customized directories.
MSG=`log_message "STANDARD" "[PERCONA][PERCONA_RELEASE][PSMDB8][POST-INSTALL]" "INFO" "Customizing ${PERCONA_HELPER_PATH} with customized mongod files path"`
echo "${MSG}"
if [[ -e ${PERCONA_HELPER_PATH} ]]; then
  MSG1=`log_message "STANDARD" "[PERCONA][PERCONA_RELEASE][PSMDB8][POST-INSTALL]" "INFO" "Customizing ${PERCONA_HELPER_PATH} Found"`
  MSG2=`log_message "STANDARD" "[PERCONA][PERCONA_RELEASE][PSMDB8][POST-INSTALL]" "INFO" "Copy ${PERCONA_HELPER_PATH} to Backup dir ${BKPINSTALLDIR}"`
  echo "${MSG1}"
  echo "${MSG2}"
  cp ${PERCONA_HELPER_PATH} ${BKPINSTALLDIR}
  sed -i 's/\/etc\/mongod.conf/\/etc\/mongod\/mongod.conf/g' ${PERCONA_HELPER_PATH}
  #sed -i 's/touch/##touch/g' ${PERCONA_HELPER_PATH}
  #sed -i 's/chown/##chown/g' ${PERCONA_HELPER_PATH}
else
  MSG=`log_message "STANDARD" "[PERCONA][PERCONA_RELEASE][PSMDB8][POST-INSTALL]" "WARNING" "${PERCONA_HELPER_PATH} not present"`
fi

# --- SELinux Configuration for Custom Paths ---
MSG=`log_message "STANDARD" "[MONGO_WORK_DIRS][SELINUX][SETUP]" "INFO" "Configuring SELinux contexts for MongoDB..."`
echo "${MSG}"

semanage fcontext -a -t mongod_var_lib_t "${MONGO_DATA_DIR}(/.*)?"
semanage fcontext -a -t mongod_log_t "${MONGO_LOG_DIR}(/.*)?"
semanage fcontext -a -t mongod_var_run_t "${MONGO_PID_DIR}(/.*)?"

restorecon -R -v ${MONGO_DATA_DIR}
restorecon -R -v ${MONGO_LOG_DIR}
restorecon -R -v ${MONGO_PID_DIR}

# Set ownership for all custom directories
MSG=`log_message "STANDARD" "[MONGO_WORK_DIRS][OWNER][SETUP]" "INFO" "Setting ownership for all MongoDB directories to mongod user"`
echo "${MSG}"
chown -R mongod:mongod ${MONGO_DATA_DIR}
chown -R mongod:mongod ${MONGO_LOG_DIR}
chown -R mongod:mongod ${MONGO_PID_DIR}

# --- Configure MongoDB ---
MSG=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE]" "INFO" "Creating new mongod.conf file..."`
echo "${MSG}"

# mongod.cnf file from installation renaming
MSG=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][CHECK]" "INFO" "Checking if default ${MONGOD_DEF_CNF_FILE} is present"`
echo "${MSG}"
if [[ -e ${MONGOD_DEF_CNF_FILE} ]]; then
  MSG1=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][CHECK]" "WARNING" "Default mongod.conf present in : ${MONGOD_DEF_CNF_FILE} !!"`
  MSG2=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][BACKUP]" "WARNING" "Copy default ${MONGOD_DEF_CNF_FILE} to ${BKPINSTALLDIR}"`
  echo "${MSG1}"
  echo "${MSG2}"
  cp ${MONGOD_DEF_CNF_FILE} ${BKPINSTALLDIR}
  if [[ $? -eq 0 ]]; then
    MSGOK=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][CHECK]" "OK" "${MONGOD_DEF_CNF_FILE} successfully copied to ${BKPINSTALLDIR}"`
    echo "${MSGOK}"
  fi
fi

if [ ! -e ${MONGO_CNF_PATH} ]; then  
  MSG=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE]" "INFO" "${MONGO_CNF_PATH} Not found! Creating File from the scratch"`
  echo "${MSG}"
else  
  MSGBKPCONF=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][BACKUP]" "INFO" "${MONGO_CNF_PATH} Found! Moving to ${BKPINSTALLDIR}"`
  echo "${MSGBKPCONF}"
  mv ${MONGO_CNF_PATH} ${BKPINSTALLDIR}
  if [[ $? -eq 0 ]]; then
     MSGOK=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][BACKUP]" "OK" "${MONGO_CNF_PATH} Moved to ${BKPINSTALLDIR}"`
     echo "${MSGOK}"
  fi
fi

MSG=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][TUNNING]" "INFO" "Tunning mongod in ${MONGO_CNF_PATH} ..."`
echo "${MSG}"

MSGCONFWT=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][WIREDTIGER]" "INFO" "Mongodb wiredTiger memory parameters calculation"`
echo "${MSGCONFWT}"
SRV_MEM=$(free -gt|grep 'Mem'|awk '{print $2}')
MONGO_WT_CACHEGB=`echo "scale=2; ${SRV_MEM} * 0.5" | bc`
# echo "*** Mongodb wiredTiger memory parameters calculation ***"
MSGMEMAVAILABLE=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][WIREDTIGER]" "INFO" "*** > Server Memory available in GB  : ${SRV_MEM}"`
MSGMEMWTCACHEGB=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][WIREDTIGER]" "OK" "*** > MongoDB wiredTiger Cache in GB : ${MONGO_WT_CACHEGB}"`
echo "${MSGMEMAVAILABLE}"
echo "${MSGMEMWTCACHEGB}"

# -- ReplicaSet Name compose
MSGCONFRS=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][REPLICASET]" "INFO" "MogoDB ReplicaSet Name creation"`
echo "${MSGCONFRS}"
MONGODB_RS_PREFIX_NAME="rs"
MONGODB_RS_PREFIX_ENV=`hostname| sed -r "${MONGODB_NODE_REGEX}\1/"`       # Environment prefix
MONGODB_RS_SUFIX_SRV=`hostname| sed -r "${MONGODB_NODE_REGEX}\2/"`        # ServiceName sufix
MONGODB_RS_NAME="${MONGODB_RS_PREFIX_ENV}${MONGODB_RS_PREFIX_NAME}${MONGODB_RS_SUFIX_SRV}"
MSGCONFRS=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][REPLICASET]" "OK" "*** > MongoDB Replica Name  : ${MONGODB_RS_NAME}"`
echo "${MSGCONFRS}"

MSGCONFRSAUTHKEY=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][REPLICASET][KEYFILE]" "INFO" "Mongodb Key file check "`
echo "${MSGCONFRSAUTHKEY}"
# -- Key file will be generated in PRIMARY node only
if [ "${is_primary}" == "yes" ]; then
  # -- Key File generation in PRIMARY node
  if [ -e ${MONGO_RS_KEYFILE_PATH} ]; then
    MSGCONFRSAUTHKEY=`log_message "STANDARD" "[MONGODB][SETUP][REPLICASET][KEYFILE]" "WARNING" "${MONGO_RS_KEYFILE_PATH} Found! Nothing to do..."`
    echo "${MSGCONFRSAUTHKEY}"
  else  
    MSGCONFRSAUTHKEY=`log_message "STANDARD" "[MONGODB][SETUP][REPLICASET][KEYFILE]" "INFO" "${MONGO_RS_KEYFILE_PATH} Not found! Creating Key File from the scratch"`
    echo "${MSGCONFRSAUTHKEY}"
    openssl rand -base64 756 > ${MONGO_RS_KEYFILE_PATH}
    if [[ $? -eq 0 ]]; then
    	MSGCONFRSAUTHKEYOK=`log_message "STANDARD" "[MONGODB][SETUP][REPLICASET][KEYFILE]" "OK" "MongoDB Key File created at : ${MONGO_RS_KEYFILE_PATH} !!"`
    	MSG=`log_message "STANDARD" "[MONGODB][SETUP][REPLICASET][KEYFILE]" "INFO" "Setting up permissions for ${MONGO_RS_KEYFILE_PATH} ..."`
    	echo "${MSGCONFRSAUTHKEY}"
    	echo "${MSG}"
    	chmod 400 ${MONGO_RS_KEYFILE_PATH}
      chown mongod:mongod ${MONGO_RS_KEYFILE_PATH}
      ### Interesting : copy to a bucket from primary and take it from secondary nodes
    	if [[ $? -eq 0 ]]; then
        MSGKEYFILEPERMOK=`log_message "STANDARD" "[MONGODB][SETUP][REPLICASET][KEYFILE]" "OK" "Permissions setted up for MongoDB Key File !!"`
        echo "${MSGKEYFILEPERMOK}"
        ls -lh ${MONGO_RS_KEYFILE_PATH}
      fi
    fi
  fi
else
  # -- Key File not generated in SECONDARY. Add entry in mongod configuration file.
  #    Report in output and remind to copy key file from Primary Node
  SECONDARYMSG1=`log_message "STANDARD" "[MONGODB][SETUP][REPLICASET][KEYFILE]" "INFO" "This node has been defined as SECONDARY"`
  SECONDARYMSG2=`log_message "STANDARD" "[MONGODB][SETUP][REPLICASET][KEYFILE]" "WARNING" "Please copy ${MONGO_RS_KEYFILE_PATH} from PRIMARY before starting MongoDB Server"`
  SECONDARYMSG3=`log_message "STANDARD" "[MONGODB][SETUP][REPLICASET][KEYFILE]" "INFO" "Key file path will be added to mongod configuration file"`
  echo "${SECONDARYMSG1}"
  echo "${SECONDARYMSG2}"
  echo "${SECONDARYMSG3}"
fi


# Create a new, complete mongod.conf 
MSG=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][TUNNING][CREATION]" "INFO" "Creating mongod.conf file in: ${MONGO_CNF_PATH} ..."`
echo "${MSG}"
#mongod_confile_rewrite "${MONGO_CNF_PATH}" "${MONGO_DATA_DIR}" ${MONGO_WT_CACHEGB} "${MONGO_LOG_FILE_PATH}" "${MONGO_PID_FILE_PATH}" "${MONGO_RS_KEYFILE_PATH}" "${MONGODB_RS_NAME}"
arraymongodconf=( ${MONGO_CNF_PATH} ${MONGO_DATA_DIR} ${MONGO_WT_CACHEGB} ${MONGO_LOG_FILE_PATH} ${MONGO_PID_FILE_PATH} ${MONGO_RS_KEYFILE_PATH} ${MONGODB_RS_NAME})
mongod_confile_rewrite ${arraymongodconf[@]}
 
# -- mongod.conf file tunning check
if [[ -e ${MONGO_SERVICE_PATH} ]]; then
#  grep 'dbPath\|path\|cacheSizeGB\|pidFilePath\|keyFile\|replSetName' /etc/mongod/mongod.conf|tr -d '[[:blank:]]'|awk -F':' '{print $2}'
  MSGOK=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][TUNNING][CREATION]" "OK" "mongod.conf file created in ${MONGO_CNF_PATH} !!"`
  echo "${MSGOK}"

  DBPATHINCNF=`grep 'dbPath' ${MONGO_CNF_PATH}|tr -d '[[:blank:]]'|awk -F':' '{print $2}'`
  if [[ "$DBPATHINCNF" == "$MONGO_DATA_DIR" ]]; then
    MSGOK=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][TUNNING][VERIFY]" "OK" "dbPath -> ${MONGO_DATA_DIR} successfully added in ${MONGO_CNF_PATH} !!"`
    echo ${MSGOK}
  fi

  DBWTMEMINCNF=`grep 'cacheSizeGB' ${MONGO_CNF_PATH}|tr -d '[[:blank:]]'|awk -F':' '{print $2}'`
  if [[ "$DBWTMEMINCNF" == "$MONGO_WT_CACHEGB" ]]; then
    MSGOK=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][TUNNING][VERIFY]" "OK" "cacheSizeGB -> ${MONGO_WT_CACHEGB} successfully added in ${MONGO_CNF_PATH} !!"`
    echo ${MSGOK}
  fi
  DBLOGPATHINCNF=`grep 'path' ${MONGO_CNF_PATH}|tr -d '[[:blank:]]'|awk -F':' '{print $2}'`
  if [[ "$DBLOGPATHINCNF" == "$MONGO_LOG_FILE_PATH" ]]; then
    MSGOK=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][TUNNING][VERIFY]" "OK" "systemLog.path -> ${MONGO_LOG_FILE_PATH} successfully added in ${MONGO_CNF_PATH} !!"`
    echo ${MSGOK}
  fi
  DBPIDINCNF=`grep 'pidFilePath' ${MONGO_CNF_PATH}|tr -d '[[:blank:]]'|awk -F':' '{print $2}'`
  if [[ "$DBPIDINCNF" == "$MONGO_PID_FILE_PATH" ]]; then
    MSGOK=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][TUNNING][VERIFY]" "OK" "processManagement.pidFilePath -> ${MONGO_PID_FILE_PATH} successfully added in ${MONGO_CNF_PATH} !!"`
    echo ${MSGOK}
  fi

  DBKFINCNF=`grep 'keyFile' ${MONGO_CNF_PATH}|tr -d '[[:blank:]]'|awk -F':' '{print $2}'`
  if [[ "$DBKFINCNF" == "$MONGO_RS_KEYFILE_PATH" ]]; then
    MSGOK=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][TUNNING][VERIFY]" "OK" "security.keyFile -> ${MONGO_RS_KEYFILE_PATH} successfully added in ${MONGO_CNF_PATH} !!"`
    echo ${MSGOK}
  fi
  DBRSINCNF=`grep 'replSetName' ${MONGO_CNF_PATH}|tr -d '[[:blank:]]'|awk -F':' '{print $2}'`
  if [[ "$DBRSINCNF" == "$MONGODB_RS_NAME" ]]; then
    MSGOK=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][TUNNING][VERIFY]" "OK" "replication.replSetName -> ${MONGODB_RS_NAME} successfully added in ${MONGO_CNF_PATH} !!"`
    echo ${MSGOK}
  fi
else
  MONGODCNFMSGERR=`log_message "STANDARD" "[MONGODB][SETUP][CONFFILE][TUNNING][CREATION]" "ERROR" "mongod.conf file not found in: ${MONGO_CNF_PATH} ..."`
  EXITCODE=-3
fi

# mongodb service file renaming
MSG=`log_message "STANDARD" "[MONGODB][SERVICE][CONFIGURATION]" "INFO" "Checking if mongod service file ${MONGO_SERVICE_PATH} is present..."`
echo "${MSG}"
if [[ -e ${MONGO_SERVICE_PATH} ]]; then
  MSG1=`log_message "STANDARD" "[MONGODB][SERVICE][CONFIGURATION]" "INFO" "${MONGO_SERVICE_PATH} present!!"`
  MSG2=`log_message "STANDARD" "[MONGODB][SERVICE][CONFIGURATION][BACKUP]" "INFO" "Copying source file ${MONGO_SERVICE_PATH} to ${BKPINSTALLDIR}!!"`
  echo "${MSG1}"
  echo "${MSG2}"
  cp ${MONGO_SERVICE_PATH} ${BKPINSTALLDIR}
  if [[ $? -eq 0 ]]; then
    MSGOK=`log_message "STANDARD" "[MONGODB][SERVICE][CONFIGURATION][BACKUP]" "OK" "${MONGO_SERVICE_PATH} copied to ${BKPINSTALLDIR}!!"`
    echo "${MSGOK}"
  fi
fi

# --- New Mongodb service file
MSG=`log_message "STANDARD" "[MONGODB][SERVICE][CONFIGURATION]" "INFO" "Recreating ${MONGO_SERVICE_PATH}..."`
echo "${MSG}"
mongod_service_file "${MONGO_SERVICE_PATH}"
if [[ -e ${MONGO_SERVICE_PATH} ]]; then
  MSGOK=`log_message "STANDARD" "[MONGODB][SERVICE][CONFIGURATION]" "OK" "Recreating ${MONGO_SERVICE_PATH}..."`
fi


# mongod environment file rewrite for using new mongod.cnf path file
# 
MONGOD_ENV_FILE=`grep 'EnvironmentFile' /usr/lib/systemd/system/mongod.service|awk -F'-' '{print $2}'`
if [[ -e ${MONGOD_ENV_FILE} ]]; then
  OLD_MONGOD_ENV_FILE="${MONGOD_ENV_FILE}.source"
  cp ${MONGOD_ENV_FILE} ${OLD_MONGOD_ENV_FILE}
  sed -i 's/\/etc\/mongod.conf/\/etc\/mongod\/mongod.conf/g' ${MONGOD_ENV_FILE}
fi

systemctl daemon-reload
# --- Start Service and Initiate Replica Set ---
# echo "Starting mongod service..."
# systemctl restart mongod
# systemctl enable mongod

# if [ "${is_primary}" == "yes" ]; then
#   echo "This is the primary node. Initiating replica set..."
#   sleep 20
#   mongosh --eval 'rs.initiate({ _id: "${replica_set_name}", members: [ ${member_list} ] })'
#   echo "Replica set initiated successfully."

#   # Create the user for Percona Backup for MongoDB
#   echo "Creating Percona Backup user..."
#   mongosh --eval 'db.getSiblingDB("admin").createUser({user: "pbmuser", pwd: "pbmpassword", roles: [{role: "clusterAdmin", db: "admin"}, {role: "readWriteAnyDatabase", db: "admin"}, {role: "userAdminAnyDatabase", db: "admin"}]})'
#   echo "Backup user created."

# else
#   echo "This is a secondary node. It will be added to the replica set by the primary."
# fi

# --- Log Rotate for mongodb Log setup ---
LOGROATECONFMSGCHECK=`log_message "STANDARD" "[LOGROTATE][MONGODB][CONFFILE][CREATION][CHECK]" "INFO" "Checking Logrotate configuration for mongod service is already present"`
LOGROATECONFMSG1=`log_message "STANDARD" "[LOGROTATE][MONGODB][CONFFILE][CREATION]" "INFO" "Creating Logrotate configuration for mongod service..."`
LOGROATECONFMSG2=`log_message "STANDARD" "[LOGROTATE][MONGODB][CONFFILE][CREATION]" "INFO" " > Log rotate conf file -> ${MONGOD_LOGROTATE_CNF}"`
LOGROATECONFMSG3=`log_message "STANDARD" "[LOGROTATE][MONGODB][CONFFILE][CREATION]" "INFO" " > mongod log file path -> ${MONGO_LOG_FILE_PATH}"`
LOGROATECONFMSG4=`log_message "STANDARD" "[LOGROTATE][MONGODB][CONFFILE][CREATION]" "INFO" " > mongod pid file path -> ${MONGO_PID_FILE_PATH}"`

echo "$LOGROATECONFMSGCHECK"
if [[ -e ${MONGOD_LOGROTATE_CNF} ]]; then
  LOGROATECONFMSCHECKGOK=`log_message "STANDARD" "[LOGROTATE][MONGODB][CONFFILE][CREATION]" "WARNING" " Logrotate configuration file: ${MONGOD_LOGROTATE_CNF} Already Created...Nothing to do!"`
  echo ${LOGROATECONFMSCHECKGOK}
else
  echo "${LOGROATECONFMSG1}"
  echo "${LOGROATECONFMSG2}"
  echo "${LOGROATECONFMSG3}"
  echo "${LOGROATECONFMSG4}"
  arraylogrotate=( ${MONGOD_LOGROTATE_CNF} ${MONGO_LOG_FILE_PATH} ${MONGO_PID_FILE_PATH} )
  mongod_logrotate_setup ${arraylogrotate[@]}
  if [[ ! -s ${MONGOD_LOGROTATE_CNF} ]]; then
    LOGROATECONFMSGERR=`log_message "STANDARD" "[LOGROTATE][MONGODB][CONFFILE][CREATION]" "ERROR" " Logrotate configuration file: ${MONGOD_LOGROTATE_CNF} Not Created!!"`
    echo "${LOGROATECONFMSGERR}"
    ERRORCODE=-5
  else
    LOGROATECONFMSGOK=`log_message "STANDARD" "[LOGROTATE][MONGODB][CONFFILE][CREATION]" "OK" " Logrotate configuration file: ${MONGOD_LOGROTATE_CNF} Created!! "`
    echo ${LOGROATECONFMSGOK}
  fi
fi

ENDMSGOK=`log_message "STANDARD" "[MONGODB][PROVISION][STARTUP][FINISHED]" "OK" "Startup script finished!!"`
echo ${ENDMSGOK}
# ipa-client-install --uninstall
