MONGOSHBINPATH=`which mongosh`
export MONGOADMINUSR="admin"
export MONGOADMINPAS="6UAvkhAwxm2gfF4BcGNWhEaIbRAZOr2C"
export ADMINDB="admin"
export MONGOHOST="cd-mongodbcluster01/cd-mongodbcluster01-node01.betika.private,cd-mongodbcluster01-node02.betika.private,cd-mongodbcluster01-node03.betika.private"
