MONGOSHBINPATH=`which mongosh`
export MONGOADMINUSR="admin"
export MONGOADMINPAS="aoIuoszOl0NNzfI2ceNlmYcpabxZcx4Q"
export ADMINDB="admin"
export MONGOHOST="ug-mongodbcluster01/ug-mongodbcluster01-node01.betika.private,ug-mongodbcluster01-node02.betika.private,ug-mongodbcluster01-node03.betika.private"
