MONGOSHBINPATH=`which mongosh`
export MONGOADMINUSR="admin"
export MONGOADMINPAS="6ihrq0KUX7EZiVR8zu7xZR6ygl5xhakJ"
export ADMINDB="admin"
export MONGOHOST="ke-mongodbcluster/ke-mongodbcluster01.betika.private,ke-mongodbcluster02.betika.private,ke-mongodbcluster03.betika.private"
