#!/usr/bin/env bash
# =============================================================================
# migration_commands.sh - generated by betika_mongodb_normalized (@@GENERATED_AT@@)
#
# Moves every source database to the central target with
#   mongodump --archive | mongorestore --nsFrom/--nsTo
# DRY-RUN by default (prints the commands). Compatible with bash >= 3.2.
# =============================================================================
set -euo pipefail

readonly SCRIPT_NAME="$(basename "$0")"
readonly BLOCKING_ERRORS=@@BLOCKING_ERRORS@@
BMN_TOOLS_CFG_DIR="${BMN_TOOLS_CFG_DIR:-${HOME}/.config/betika_mongodb_normalized/tools}"

# --- Connection config files (database-tools YAML, chmod 600) -----------------
# Each file contains ONLY the connection string, credentials included:
#   uri: "mongodb://<user>:<password>@<hosts>/?authSource=admin&replicaSet=<rs>"
# Privileges: built-in role 'backup' on sources, 'restore' on the target.
CFG_TARGET="${CFG_TARGET:-${BMN_TOOLS_CFG_DIR}/target.yaml}"
@@SOURCE_CONFIGS@@

# --- Jobs: alias|source_db|target_db -------------------------------------------
JOBS=(
@@JOBS@@
)

APPLY=0
FORCE=0
LIST_ONLY=0
WORKERS=4
JOB_FILTER="*"

if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; BLUE=$'\033[34m'; CYAN=$'\033[36m'; BOLD=$'\033[1m'; RESET=$'\033[0m'
else
  RED=""; GREEN=""; YELLOW=""; BLUE=""; CYAN=""; BOLD=""; RESET=""
fi

log_info()  { printf '%s[INFO]%s %s\n' "${BLUE}" "${RESET}" "$*"; }
log_ok()    { printf '%s[ OK ]%s %s\n' "${GREEN}" "${RESET}" "$*"; }
log_warn()  { printf '%s[WARN]%s %s\n' "${YELLOW}" "${RESET}" "$*" >&2; }
log_error() { printf '%s[FAIL]%s %s\n' "${RED}" "${RESET}" "$*" >&2; }

usage() {
  cat <<EOF
${BOLD}${SCRIPT_NAME}${RESET} - move source databases to the central MongoDB instance

${BOLD}USAGE${RESET}
  ${SCRIPT_NAME} [options]

${BOLD}OPTIONS${RESET}
  -a, --apply          Execute the jobs (default: dry-run, print commands only)
  -f, --force          Allow --apply even if the analysis reported blocking errors
  -j, --job PATTERN    Only run jobs whose "alias:source_db" matches the glob PATTERN
  -w, --workers N      mongorestore --numInsertionWorkersPerCollection (default: ${WORKERS})
  -l, --list           List jobs and exit
      --no-color       Disable colored output
  -h, --help           Show this help

${BOLD}ENVIRONMENT${RESET}
  BMN_TOOLS_CFG_DIR    Directory with the database-tools YAML files (default: ${BMN_TOOLS_CFG_DIR})
  CFG_TARGET, CFG_<ALIAS>   Override an individual YAML file

${BOLD}RECOMMENDED ORDER${RESET}
  1. BMN_PHASE=collections BMN_APPLY=1 mongosh <target> --file target_bootstrap.js
  2. ${SCRIPT_NAME} --apply        (writes frozen on sources: no --oplog, not point-in-time)
  3. BMN_PHASE=indexes / views / security / verify ... target_bootstrap.js

${BOLD}EXAMPLES${RESET}
  ${SCRIPT_NAME} --list
  ${SCRIPT_NAME} --job 'cd01:*'
  ${SCRIPT_NAME} --apply --job 'cd01:orders' --workers 8
EOF
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -a|--apply) APPLY=1 ;;
      -f|--force) FORCE=1 ;;
      -l|--list) LIST_ONLY=1 ;;
      -j|--job) JOB_FILTER="${2:?--job requires a value}"; shift ;;
      -w|--workers) WORKERS="${2:?--workers requires a value}"; shift ;;
      --no-color) RED=""; GREEN=""; YELLOW=""; BLUE=""; CYAN=""; BOLD=""; RESET="" ;;
      -h|--help) usage; exit 0 ;;
      *) log_error "unknown option: $1"; usage; exit 2 ;;
    esac
    shift
  done
  if ! [[ "${WORKERS}" =~ ^[0-9]+$ ]] || [[ "${WORKERS}" -lt 1 ]]; then
    log_error "--workers must be a positive integer"; exit 2
  fi
}

upper() { printf '%s' "$1" | tr '[:lower:]' '[:upper:]'; }

check_cfg() {
  local file="$1" perms
  if [[ ! -r "${file}" ]]; then
    log_error "config file not readable: ${file}"; return 1
  fi
  if perms="$(stat -c '%a' "${file}" 2>/dev/null)" || perms="$(stat -f '%Lp' "${file}" 2>/dev/null)"; then
    case "${perms}" in
      600|400) ;;
      *) log_warn "${file} has mode ${perms}; use chmod 600" ;;
    esac
  fi
}

run_job() {
  local alias="$1" sdb="$2" tdb="$3"
  local var src_cfg
  var="CFG_$(upper "${alias}")"
  src_cfg="${!var:-}"
  local -a dump_args=(--config="${src_cfg}" --db="${sdb}" --archive --gzip)
  local -a restore_args=(--config="${CFG_TARGET}" --archive --gzip --nsInclude="${sdb}.*"
    --noIndexRestore --bypassDocumentValidation --numInsertionWorkersPerCollection="${WORKERS}")
  if [[ "${sdb}" != "${tdb}" ]]; then
    restore_args+=(--nsFrom="${sdb}.*" --nsTo="${tdb}.*")
  fi

  printf '%s==>%s %s%s:%s%s -> %s%s%s\n' "${CYAN}" "${RESET}" "${BOLD}" "${alias}" "${sdb}" "${RESET}" "${BOLD}" "${tdb}" "${RESET}"
  if [[ "${APPLY}" -eq 0 ]]; then
    printf '    mongodump'; printf ' %q' "${dump_args[@]}"; printf ' \\\n'
    printf '      | mongorestore'; printf ' %q' "${restore_args[@]}"; printf '\n'
    return 0
  fi
  check_cfg "${src_cfg}"
  check_cfg "${CFG_TARGET}"
  local start end
  start="$(date +%s)"
  if mongodump "${dump_args[@]}" | mongorestore "${restore_args[@]}"; then
    end="$(date +%s)"
    log_ok "${alias}:${sdb} -> ${tdb} ($((end - start))s)"
  else
    log_error "${alias}:${sdb} -> ${tdb} failed"
    return 1
  fi
}

main() {
  parse_args "$@"
  if [[ ${#JOBS[@]} -eq 0 ]]; then
    log_warn "no jobs defined"; exit 0
  fi
  if [[ "${APPLY}" -eq 1 && "${BLOCKING_ERRORS}" -gt 0 && "${FORCE}" -eq 0 ]]; then
    log_error "analysis reported ${BLOCKING_ERRORS} blocking error(s); fix them or use --force"
    exit 3
  fi
  if [[ "${APPLY}" -eq 1 ]]; then
    local bin
    for bin in mongodump mongorestore; do
      command -v "${bin}" >/dev/null 2>&1 || { log_error "${bin} not found in PATH"; exit 4; }
    done
  fi

  log_info "mode=$([[ "${APPLY}" -eq 1 ]] && echo APPLY || echo DRY-RUN) filter='${JOB_FILTER}' workers=${WORKERS}"
  local job alias sdb tdb failed=0 done_jobs=0
  for job in ${JOBS[@]+"${JOBS[@]}"}; do
    IFS='|' read -r alias sdb tdb <<<"${job}"
    # shellcheck disable=SC2053
    [[ "${alias}:${sdb}" == ${JOB_FILTER} ]] || continue
    if [[ "${LIST_ONLY}" -eq 1 ]]; then
      printf '%-24s %-32s -> %s\n' "${alias}" "${sdb}" "${tdb}"
      continue
    fi
    done_jobs=$((done_jobs + 1))
    run_job "${alias}" "${sdb}" "${tdb}" || failed=$((failed + 1))
  done
  [[ "${LIST_ONLY}" -eq 1 ]] && exit 0
  if [[ "${failed}" -gt 0 ]]; then
    log_error "${failed}/${done_jobs} job(s) failed"; exit 1
  fi
  log_ok "${done_jobs} job(s) processed"
}

main "$@"
